version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - payment-network

  online-payment-service:
    container_name: online-payment-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - payment-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge
