import { useState, useEffect } from 'react';
import { Scale, BookOpen, ArrowLeft, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function TermsOfServicePage() {
  const [termsText, setTermsText] = useState('');
  const [appName, setAppName] = useState('');

  useEffect(() => {
    const savedName = localStorage.getItem('legal_app_name') || 'Daily Meal Recipe';
    const savedEntity = localStorage.getItem('legal_entity_name') || 'Daily Meal Recipe LLC';
    const savedEmail = localStorage.getItem('legal_support_email') || 'info@dailymealrecipe.online';
    setAppName(savedName);

    // Initial default draft matching the custom generator
    const defaultTerms = `TERMS OF SERVICE AGREEMENT

Last Updated: May 2026

Welcome to ${savedName}! This Agreement governs your legal usage of the meal organizer platforms, pantry organization trackers, and generative recipes provided by ${savedEntity}.

1. GENERAL USE & REGISTRATION OBLIGATIONS
To create an account, you must hold correct authorization. You agree to protect your culinary credentials and refrain from automated database queries, recipe scraping, or script injections.

2. SUB-REGISTRATION & TRANSACTIONS
Access to pro recipe generation is billed on a recurring sub-basis. Cancelations must be submitted securely before renew timings.

3. KITCHEN LIABILITY & ALLERGEN DISCLAIMER
Our culinary recommendations are generated by language intelligence and scanners. It is your ultimate, absolute responsibility to check raw ingredients and ensure safe handling. 我们 accepts zero civil or medical liability for allergies, dietary disputes, foodborne issues, or preparations.

4. ARBITRATION
Any disputes arising under these terms will be settled privately with professional mediation desks before court-house litigation.

Should you require account support, mail legal enquiries details to ${savedEmail}.`;

    const savedTerms = localStorage.getItem('legal_terms_draft') || defaultTerms;
    setTermsText(savedTerms);
  }, []);

  return (
    <div className="min-h-screen bg-onyx py-12 px-4 sm:px-6 text-slate-100">
      <div className="max-w-3xl mx-auto space-y-8">
        
        {/* Nav actions */}
        <div className="flex items-center justify-between">
          <Link 
            to="/" 
            className="inline-flex items-center gap-2 text-xs uppercase font-bold tracking-wider text-amber-accent/70 hover:text-amber-accent transition-all duration-200"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Kitchen</span>
          </Link>

          <Link 
            to="/compliance" 
            className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-white/5 border border-white/5 hover:border-white/15 rounded-xl text-[10px] font-black uppercase tracking-wider text-slate-300 transition-all"
          >
            <span>Legal Desk Hub</span>
            <ExternalLink className="w-3 h-3" />
          </Link>
        </div>

        {/* Paper Layout Card */}
        <div className="relative p-8 sm:p-10 rounded-3xl bg-gradient-to-b from-stone-900 to-stone-950 border border-white/5 shadow-2xl overflow-hidden leading-relaxed">
          <div className="absolute top-0 right-0 w-60 h-60 bg-amber-accent/5 rounded-full blur-[100px] pointer-events-none" />
          
          <div className="space-y-6">
            <div className="flex items-center gap-3 border-b border-white/5 pb-5">
              <div className="p-3 bg-amber-accent/10 text-amber-accent rounded-2xl">
                <Scale className="w-6 h-6" />
              </div>
              <div className="space-y-1">
                <h1 className="font-serif text-2xl font-light text-white">Terms of Service</h1>
                <p className="text-[10px] uppercase font-mono tracking-widest text-slate-400">
                  Daily Meal Recipe Public Publication • Platform Rules of Engagement
                </p>
              </div>
            </div>

            {/* Render with neat spacing */}
            <div className="whitespace-pre-wrap font-sans text-xs sm:text-sm text-slate-300 hover:text-white leading-relaxed space-y-4 font-light">
              {termsText}
            </div>

            {/* Extra Disclaimer Box */}
            <div className="p-4 rounded-xl bg-white/[0.01] border border-white/5 text-[10px] text-slate-400 space-y-1.5">
              <span className="font-bold text-white uppercase tracking-wider block">ALLERGEN HEALTH SAFETY LIMITS</span>
              <p>
                By using {appName}, you explicitly acknowledge that recipe suggestions are provided as advisory suggestions only. Always cross-verify nutritional breakdowns and allergen flags manually. Do not configure dietary selections blindly.
              </p>
            </div>
          </div>
        </div>

        {/* Footer info */}
        <div className="text-center text-[10px] text-slate-500 uppercase font-mono tracking-widest">
          © {new Date().getFullYear()} {appName} • All Rights Reserved.
        </div>
      </div>
    </div>
  );
}
